language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.1
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --ignore=E501,E225 --exclude=registration ."

script: python setup.py test
